//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA.
        /// </summary>
        internal static string ALTA {
            get {
                return ResourceManager.GetString("ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAJA.
        /// </summary>
        internal static string BAJA {
            get {
                return ResourceManager.GetString("BAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y Contraseña pueden no ser correctos.
        /// </summary>
        internal static string CartelDos {
            get {
                return ResourceManager.GetString("CartelDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los datos son obligatorios para poder Loguearse.
        /// </summary>
        internal static string CartelTres {
            get {
                return ResourceManager.GetString("CartelTres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha Iniciado sesión correctamente.
        /// </summary>
        internal static string CartelUno {
            get {
                return ResourceManager.GetString("CartelUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO.
        /// </summary>
        internal static string CÓDIGO {
            get {
                return ResourceManager.GetString("CÓDIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO DE AREA.
        /// </summary>
        internal static string CÓDIGO_DE_AREA {
            get {
                return ResourceManager.GetString("CÓDIGO DE AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA.
        /// </summary>
        internal static string CONTRASEÑA {
            get {
                return ResourceManager.GetString("CONTRASEÑA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMA.
        /// </summary>
        internal static string IDIOMA {
            get {
                return ResourceManager.GetString("IDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET IN.
        /// </summary>
        internal static string INGRESAR {
            get {
                return ResourceManager.GetString("INGRESAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LISTA DE LOCALIDADES.
        /// </summary>
        internal static string LISTA_DE_LOCALIDADES {
            get {
                return ResourceManager.GetString("LISTA DE LOCALIDADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOCALIDAD.
        /// </summary>
        internal static string LOCALIDAD {
            get {
                return ResourceManager.GetString("LOCALIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODIFICACIÓN.
        /// </summary>
        internal static string MODIFICACIÓN {
            get {
                return ResourceManager.GetString("MODIFICACIÓN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE.
        /// </summary>
        internal static string NOMBRE {
            get {
                return ResourceManager.GetString("NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVO USUARIO.
        /// </summary>
        internal static string NUEVO_USUARIO {
            get {
                return ResourceManager.GetString("NUEVO USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        internal static string SALIR {
            get {
                return ResourceManager.GetString("SALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIO.
        /// </summary>
        internal static string USUARIO {
            get {
                return ResourceManager.GetString("USUARIO", resourceCulture);
            }
        }
    }
}
